name: iqamah
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.8+22

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_compass: ^0.8.0
 
  intl: ^0.17.0
  http: ^1.3.0
  flutter_html: ^3.0.0
  markdown: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  url_launcher: ^6.1.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.0
  firebase_messaging: ^15.2.5
  flutter_native_splash: ^2.4.6
  ollama_dart: ^0.2.2+1 
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/eic_logo_1024.png"

flutter_native_splash:
  image: "assets/images/eic_logo_splash1.png"
  color: "#ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11


flutter:

  uses-material-design: true

  assets:
    - assets/images/
  
