// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATPq-rvB8kVgZ_y5E2eTtXV4HbvcPACaw',
    appId: '1:608602112137:android:93567354b53ee1cc508658',
    messagingSenderId: '608602112137',
    projectId: 'eiciqamah',
    storageBucket: 'eiciqamah.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmN2KVr9pZJQ3aAJo02e09C5abPIf_DAU',
    appId: '1:608602112137:ios:5b347df58ecd5859508658',
    messagingSenderId: '608602112137',
    projectId: 'eiciqamah',
    storageBucket: 'eiciqamah.appspot.com',
    iosClientId: '608602112137-ibkhfohk0mto5iejd5k2t3hf1grttr17.apps.googleusercontent.com',
    iosBundleId: 'org.eicsanjose.iqamah.iqamah',
  );
}
